### PR TITLE
Updating email address

### PR DESCRIPTION
**Pull request by fishcharlie**

### CODE REVIEW

**Comment by chrisguttandin** [comment]
Hi @fishcharlie,
in case you wonder where your name and email in the list of contributors are coming from, I have a small script which scans the git history and makes sure every author of a commit is listed. I just think that's fair.
The email I used is the one which appears in the git history. However I can still change it. Do you want me to do that? The other one will still be in the git history, though. I can also remove your name entirely if you don't want to be listed. It's all up to you. :-)

**Comment by fishcharlie** [comment]
@chrisguttandin I don't mind being listed! I still would like to have it changed. I try to advertise the email address `fishcharlie.code@gmail.com` more than the other one. The other one is not really in use anymore. So it's more just to give people a better way to contact me, so that I will reply faster. I feel like it'd be a bit too much work to change it in my Git logs. So I just try to advertise the correct one.

The goal of this PR is just to give people a better way to contact me, not to obscure anything. But thank you for double checking!

**Comment by chrisguttandin** [comment]
Ok, no problem. I'm happy to change it. I can also run a script like [this](https://help.github.com/articles/changing-author-info/) to change the email in each of your commits. This will require every fork to be rebased as well but since we need to do it anyway, I don't have any problems with that. Should I do it?

**Comment by fishcharlie** [comment]
@chrisguttandin Sure! I have no problems with that. Thanks!!

**Comment by chrisguttandin** [comment]
Alright, I updated the repo to use your new email everywhere. In case you haven't done it already, you probably also want to update your local settings as described here: https://help.github.com/articles/setting-your-commit-email-address-in-git/.

**Pull request closed without merging**
